name: CI

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop

  workflow_dispatch:

jobs:
  build_and_test:
    name: Test plugin on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # show all errors for each platform (vs. cancel jobs on error)
      matrix:
        os: [macOS-latest]  # TODO: enable other OSes [ubuntu-latest, windows-2019, macOS-latest] 
    
    steps:
    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Get latest Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Init repo
      shell: bash
      run: ./repo-init.sh

    - name: Configure Build (Ninja)
      shell: bash
      run: cmake -B build-ninja -S . -G Ninja

    - name: Build CMake (Ninja)
      shell: bash
      run: cmake --build build-ninja